import subprocess
import os


def run_IESA_change_name_files(i, command, original_name_output, original_name_input, output_basename, input_basename, map_name_IESA):
    """
    Runs the AIMMS IESA-Opt model, then renames and moves the input and output Excel files
    for the current iteration.

    Args:
        i (int): Iteration number to include in the renamed files
        command (list): Command used to call the AIMMS executable
        original_name_output (str or Path): Path to the original output file generated by AIMMS
        original_name_input (str or Path): Path to the original input file generated by AIMMS
        output_basename (str): Base name for the output files
        input_basename (str): Base name for the input files
        map_name_IESA (Path): Directory where renamed files will be saved

    Returns:
        Path: The path to the newly renamed output file, or None if renaming fails
    """
    print(f"Iteration: {i}")
    print("Running AIMMS")

    # Start AIMMS and run IESA-Opt
    subprocess.call(command)
    print("AIMMS exited")

    # New filenames
    output_filename = f"{output_basename}{i}.xlsx"
    input_filename = f"{input_basename}{i}.xlsx"
    nno = map_name_IESA / output_filename
    nni = map_name_IESA / input_filename

    try:
        os.rename(original_name_output, nno)
        print(f"✔ Output file moved to: {nno}")
    except FileNotFoundError:
        print(f"❌ Output file not found: {original_name_output}")
        return
    except FileExistsError:
        print(f"❌ File already exists: {nno}")
    except Exception as e:
        print(f"❌ Error while renaming output: {e}")

    try:
        os.rename(original_name_input, nni)
        print(f"✔ Input file moved to: {nni}")
    except FileNotFoundError:
        print(f"❌ Input file not found: {original_name_input}")
        return
    except FileExistsError:
        print(f"❌ File already exists: {nni}")
    except Exception as e:
        print(f"❌ Error while renaming input: {e}")

    return nno  # Return the new output path of the results from IESA-Opt

